name: Update latest specification document in the website

on:
  push:
    branches:
      - 'master'

jobs:
  Make-PR:
    name: Make PR on website repository with updated latest spec
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - name: Checkout Current repository
        uses: actions/checkout@v2
        with:
          path: spec
      - name: Checkout Another repository
        uses: actions/checkout@v2
        with:
          repository: asyncapi/website
          path: website
      - name: Get latest release
        id: latest_version
        uses: abatilo/release-info-action@v1.3.0
        with:
          owner: asyncapi
          repo: spec
      - name: Copy Spec file from Current Repo to Another
        working-directory: ./website
        run: |
          cp ../spec/spec/asyncapi.md ./pages/docs/specifications/${{ steps.latest_version.outputs.latest_tag }}.md
      - name: Remove Table of Contents from Spec
        uses: actions/github-script@v3
        with:
          # require needs relative path to the script (relative to the current working directory)
          script: |
            const path = require('path');
            const scriptPath = path.resolve(process.cwd(), './spec/.github/scripts/remove-toc');
            const script = require(scriptPath);
            script(`${{ steps.latest_version.outputs.latest_tag }}`);
            const specFile = fs.readFileSync(`./website/pages/docs/specifications/${givenSpec}.md`);
            console.log(specFile); 